Repository witseie-elen4010/2022-group-lab-002, pull requests merged in 2022-05, with the labels that each got.

#36 Nhlamulo sprint 1 user signup
  __tests__/account.test.js
  index.js
  modules/accountData.js
  modules/flashMessages.js
  package-lock.json
  package.json
  public/css/home.css
  public/css/main.css
  routes/accountRoutes.js
  routes/mainRouter.js
  views/home.ejs
  views/layout.ejs
  views/login.ejs
  views/register.ejs
Labels: user-story, developer-sized-story, security

#41 Fixed game score page not showing
  index.js
Labels: bug, 1-point

#52 Simbongile sprint 2 settings page bug
  index.js
  routes/settingsRouter.js
  views/gameBoard.html
  views/settings.html
Labels: bug, 2-points

#54 Revert "Simbongile sprint 2 settings page bug"
  index.js
  routes/settingsRouter.js
  views/gameBoard.html
  views/settings.html
Labels: bug

#56 Nhlamulo sprint 2 account page
  database/config/db.js
  index.js
  modules/players.js
  package-lock.json
  package.json
  public/css/gameBoard.css
  routes/accountRoutes.js
  views/gameBoard.html
Labels: security, 2-points

#57 47 share link when sharing the points
  public/scripts/share.js
Labels: bug

#60 fix deployment can't find uri string for database
  .github/workflows/main_extremewordle.yml
  database/config/db.js
  index.js
  modules/players.js
  package-lock.json
  package.json
  public/css/gameBoard.css
  public/scripts/share.js
  routes/accountRoutes.js
  views/gameBoard.html
Labels: 2-points

#63 flash messages can be closed on click
  public/scripts/closeFlash.js
  routes/guest.js
  views/gameBoard.html
  views/home.ejs
  views/login.ejs
  views/register.ejs
Labels: 1-point

#64 fixing the enter bug on game settings page
  public/css/gameBoard.css
  public/css/settings.css
  views/gameBoard.html
  views/settings.html
Labels: bug, 2-points
